// Owner-approved offer and account policy, September 22, 2026.
export const siteConfig = {
  name: 'Novren',
  siteUrl: 'https://novren.co',
  planName: 'Novren WordPress Care',
  monthlyPrice: 399,
  onboardingFee: 0,
  currency: 'USD',
  siteLimit: 1,
  humanEditsPerMonth: 5,
  smallEditMinutes: 30,
  fitCallMinutes: 15,
  backupHistoryDays: 90,
  bookingHref: 'https://cal.com/gabe-glenn-9zwzc2/strategy-call',
  checkoutHref: 'https://buy.stripe.com/14A14ncmL9QK7KQ2G17Vm02',
  contactEmail: 'hello@novren.co',
  portal: { visible: false, href: 'https://app.novren.co' },
  updatedDate: '2026-09-22',
  updatedLabel: 'September 22, 2026',
  utmParameters: [
    'utm_source',
    'utm_medium',
    'utm_campaign',
    'utm_term',
    'utm_content',
  ],
  goodFit: [
    'One existing WordPress website for a small or local business.',
    'A reasonably functional site that needs routine care and small content changes.',
    'You can authorize access, maintain licenses, and provide content and approvals.',
  ],
  manualApproval: [
    'WooCommerce, ecommerce, or membership websites',
    'WordPress multisite networks',
    'Custom applications or unusually complex infrastructure',
    'Regulated or sensitive-data workflows',
    'Severe existing problems that need substantial repair',
  ],
  exclusions: [
    'New websites, full redesigns, and major page builds',
    'Custom plugins, applications, and major integrations',
    'Major WooCommerce or membership-system work',
    'Complex custom-code troubleshooting',
    'Large SEO projects, copywriting, and content production',
    'Branding projects and migrations unless separately agreed',
    'Hosting, domain registration, and email hosting',
    'Premium plugin and theme license costs unless separately agreed',
  ],
} as const;
export const money = (value: number) => '$' + value;
export const offerLine = '$399/month per website. No setup fee';
